# Generated by Django 3.2.7 on 2021-09-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='car',
            new_name='car_id',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='value',
            new_name='rating',
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=50),
        ),
    ]
